name: Firebase Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 22.14.0

    - name: Install Dependencies
      run: npm install

    - name: Replace Sensitive Values in environment.ts
      run: |
        sed -i 's|REPLACE_WITH_FIREBASE_API_KEY|${{ secrets.API_KEY }}|' src/environments/environment.ts
        sed -i 's|REPLACE_WITH_FIREBASE_AUTH_DOMAIN|${{ secrets.AUTH_DOMAIN }}|' src/environments/environment.ts
        sed -i 's|REPLACE_WITH_FIREBASE_DATABASE_URL|${{ secrets.DATABASE_URL }}|' src/environments/environment.ts
        sed -i 's|REPLACE_WITH_FIREBASE_PROJECT_ID|${{ secrets.PROJECT_ID }}|' src/environments/environment.ts
        sed -i 's|REPLACE_WITH_FIREBASE_STORAGE_BUCKET|${{ secrets.STORAGE_BUCKET }}|' src/environments/environment.ts
        sed -i 's|REPLACE_WITH_FIREBASE_MESSAGING_SENDER_ID|${{ secrets.MESSAGING_SENDER_ID }}|' src/environments/environment.ts
        sed -i 's|REPLACE_WITH_FIREBASE_APP_ID|${{ secrets.APP_ID }}|' src/environments/environment.ts
        sed -i 's|REPLACE_WITH_FIREBASE_MEASUREMENT_ID|${{ secrets.MEASUREMENT_ID }}|' src/environments/environment.ts
        sed -i 's|REPLACE_WITH_FASTAPI_URL|${{ secrets.API_URL }}|' src/environments/environment.ts

    - name: Build Angular Project
      run: npx ng build --configuration=production
    
    - name: Install Firebase CLI
      run: npm install -g firebase-tools
    
  

    - name: Deploy to Firebase
      run: firebase deploy --only hosting --token ${{ secrets.FIREBASE_DEPLOY_TOKEN }}
